name: Build Cache

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Cache Win64
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Get/Restore cache
      id: cache
      uses: actions/cache@v1.1.0
      with:
        path: Library
        key: Library-Win64
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          Library-
    - name: Download Affdex.zip and extract
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        chmod +x ./CI/AffdexDownload.sh
        ./CI/AffdexDownload.sh
        unzip -o Affdex.zip
    - name: Build with Unity
      if: steps.cache.outputs.cache-hit != 'true'
      uses: webbertakken/unity-builder@v1.0
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        unityVersion: 2018.4.17f1
        targetPlatform: StandaloneWindows64
        allowDirtyBuild: true
        buildName: Surefire Survive
        buildMethod: BuildEditor.NoBuild