name: Build Game

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Get/Restore cache
      uses: actions/cache@v1.1.0
      with:
        path: Library
        key: Library-Win64
    - name: Install unzip
      run: sudo apt-get install unzip -y
    - name: Download Affdex.zip and extract
      run: |
        chmod +x ./CI/AffdexDownload.sh
        ./CI/AffdexDownload.sh
        unzip -o Affdex.zip

    - name: Build with Unity
      uses: webbertakken/unity-builder@1.0
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        unityVersion: 2018.4.17f1
        targetPlatform: StandaloneWindows64
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Build # optional
        # A file, directory or wildcard pattern that describes what to upload
        path: build